### ISSUE TITLE
compiling freetype issue

### ISSUE THREAD

**Issue by cardypastee** [nukejunkliver/nukeparadise#3]
1>LINK : fatal error LNK1104: can't open file "freetype.lib"

**Comment by Ebzdyberybencjusz** [comment]
Maybe include it? Use FUCKING brain pls

**Comment by nukejunkliver** [comment]
Slushaj bichik, tebe ne nadoelo vsyakuyu hujnyu pisat'? Idi v shkolu davaj, maloletka ty nenormal'naya. Nikakih prufov chto ksgosimpl, nikakih prufov chto pizzhenoe menyu. CHe ty dokazat' pytaesh'sya? CHto ty daun? Molodec, dokazal
