### ISSUE TITLE
Aimbot clamp angles

### ISSUE THREAD

**Issue by Ebzdyberybencjusz** [nukejunkliver/nukeparadise#4]
Legit aim is causing ban after w game, sometimes few rounds.

**Comment by nukejunkliver** [comment]
`Math::FixAngles(cmd->viewangles);

Math::ClampAngles(cmd->viewangles);

Math::FixAngles(cmd->viewangles);

Math::ClampAngles(cmd->viewangles);

Math::FixAngles(cmd->viewangles);

Math::ClampAngles(cmd->viewangles);

Math::FixAngles(cmd->viewangles);

Math::ClampAngles(cmd->viewangles);

Math::FixAngles(cmd->viewangles);

Math::ClampAngles(cmd->viewangles);

Math::FixAngles(cmd->viewangles);

Math::ClampAngles(cmd->viewangles);`
paste this to the end createmove hook lmao
(idk i don't have a ban)

**Comment by Ebzdyberybencjusz** [comment]
Its already added
